version: "3.9"
name: MyMovies

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes: 
      - ../volumes/postgresdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - "8080:${PGADMIN_PORT}"
    volumes:
      - ../volumes/pgadmindata:/var/lib/pgadmin
    depends_on:
      - postgres

  # redis:
  #   image: redis
  #   container_name: redis
  #   command: redis-server --requirepass ${REDIS_PASS}
  #   ports: 
  #     - ${REDIS_PORT}:${REDIS_PORT}
  #   environment:
  #     - REDIS_HOST=${REDIS_HOST}
  #     - REDIS_PORT=${REDIS_PORT}
      
volumes:
  postgresdata:
  pgadmindata: